name: Deploy static to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare deploy folder
        run: |
          set -e
          rm -rf deploy
          mkdir -p deploy
          cp src/main/resources/templates/index.html deploy/index.html
          if [ -d "src/main/resources/static" ]; then
            cp -r src/main/resources/static/* deploy/
          fi
          echo "Deploy contents:" && find deploy -maxdepth 2 -type f -print

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./deploy
