name: Deploy static to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare deploy folder
        run: |
          rm -rf deploy
          mkdir -p deploy
          # Copy HTML
          cp src/main/resources/templates/index.html deploy/index.html
          # Copy ALL static files while keeping structure
          cp -r src/main/resources/static/* deploy/
          echo "Final deploy structure:"
          find deploy -type f

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./deploy
